### PR TITLE
Fix attoparsec-iso8601 and add travis build

### LINKED ISSUE #761: Cannot build attoparsec-iso8601 on master
When attempting to build the `attoparsec-iso8601` library on commit 6bd27358bf0e990fdab339158f925452e8900c3d, I get the following build error:

```
$ /opt/cabal/3.0/bin/cabal build attoparsec-iso8601
Build profile: -w ghc-8.8.3 -O1
In order, the following will be built (use -v for more details):
 - attoparsec-iso8601-1.0.1.0 (lib) (first run)
Preprocessing library for attoparsec-iso8601-1.0.1.0..
Building library for attoparsec-iso8601-1.0.1.0..
[1 of 2] Compiling Data.Attoparsec.Time.Internal ( Data/Attoparsec/Time/Internal.hs, /home/rgscott/Documents/Hacking/Haskell/aeson/dist-newstyle/build/x86_64-linux/ghc-8.8.3/attoparsec-iso8601-1.0.1.0/build/Data/Attoparsec/Time/Internal.o )

Data/Attoparsec/Time/Internal.hs:24:1: error:
    Could not load module ‘Data.Time.Clock.Compat’
    It is a member of the hidden package ‘time-compat-1.9.3’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.3’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.3’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.2.2’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.2.2’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘time-compat-1.9.2.2’.
    Perhaps you need to add ‘time-compat’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
24 | import Data.Time.Clock.Compat
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is there a missing dependency on `time-compat` somewhere?

### PR DESCRIPTION
**Pull request by bergmark**
Fixes #761

### CODE REVIEW

File: travis/script.sh [hunk 1]
```diff
@@ -19,7 +19,11 @@ case $BUILD in
     SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
       (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
     ;;
-  cabal2) 
+  cabal2)
+    cabal v2-build --enable-tests --enable-benchmarks
+    cabal v2-test --enable-tests --enable-benchmarks
+    ;;
+  attoparsec-iso8601)
```
Comment (RyanGlScott) [inline travis/script.sh]: Adding another configuration just to build `attoparsec-iso8601` seems like overkill to me. Wouldn't it suffice to just call `cabal v2-build all` in the `cabal2` configuration? Or am I missing something?

Comment (bergmark) [reply travis/script.sh]: Eh I thought there was a reason to it like this, but I think you're right.
